Parameters:
  Name:
    Description: Glue Job name
    Type: String
  Scriptlocation:
    Type: String
  GlueVersion:
    Type: String
  PythonVersion:
    Type: String
  ETLlanguage:
    Type: String
  TemporaryDirectory:
    Type: String
  PythonLibPath:
    Type: String
  JarLibPath:
    Type: String
  JobParameters:
    Type: String
  additionalPythonModules:
    Type: String
  Connections:
    Type: String
  MaximumCapacity:
    Type: String
  WorkerType:
    Type: String
  NumberOfWorkers:
    Type: String
  JobTimeout:
    Type: String
Description: AWS Glue Job Test2
Resources:
  MyJobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - glue.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"
  MyJob:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        ScriptLocation:
          Ref: Scriptlocation  
      DefaultArguments:
        "--job-bookmark-option": job-bookmark-enable
        "--extra-py-files": s3://aws-glue-scripts//testpyfiles
        "--extra-jars": s3://aws-glue-scripts//testpyfiles
        "--extra-files": s3://aws-glue-scripts//testpyfiles
        "--TempDir": s3://aws-glue-scripts//testpyfiles
      ExecutionProperty:
        MaxConcurrentRuns: 2
      MaxRetries: 0
      Name:
        Ref: Name
      Role:
        Ref: MyJobRole
      GlueVersion:
        Ref: GlueVersion
